### ISSUE TITLE
Complete the initial checklist

### ISSUE THREAD

**Issue by gautada** [gautada/drone-container#34]
### Checklist

- [x] README conforms to the [gist](https://gist.github.com/gautada/ec549c846e8e50daf355d01b06eb0665)
- [x] .gitignore conforms to the [gist](https://gist.github.com/gautada/3a0a4a76d3c7e4539e71fc02c7f599ad)
- [x] Volume folders are present (development-volume & backup-volume)
- [x] docker-compose(.yml) works
- [x] Manifst folder present (and origin to private repository is correct
- [x] Issue List is linked to proper URI
- [x] Signoff ({date and signature of last check})
